services:
    qdrant:
        image: qdrant/qdrant:latest
        restart: always
        container_name: qdrant
        ports:
            - 6333:6333
            - 6334:6334
        volumes:
            - ./qdrant_data:/qdrant/storage

    app:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sales-ai-agent
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - QDRANT_HOST=${QDRANT_HOST}
        depends_on:
            - qdrant
